// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.9
// source: agent.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VSwitchClient is the client API for VSwitch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VSwitchClient interface {
	AddBridge(ctx context.Context, in *AddBridgeRequest, opts ...grpc.CallOption) (*Response, error)
	DelBridge(ctx context.Context, in *DelBridgeRequest, opts ...grpc.CallOption) (*Response, error)
	AddBridgePort(ctx context.Context, in *AddBridgePortRequest, opts ...grpc.CallOption) (*Response, error)
	DelBridgePort(ctx context.Context, in *DelBridgePortRequest, opts ...grpc.CallOption) (*Response, error)
}

type vSwitchClient struct {
	cc grpc.ClientConnInterface
}

func NewVSwitchClient(cc grpc.ClientConnInterface) VSwitchClient {
	return &vSwitchClient{cc}
}

func (c *vSwitchClient) AddBridge(ctx context.Context, in *AddBridgeRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.VSwitch/AddBridge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vSwitchClient) DelBridge(ctx context.Context, in *DelBridgeRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.VSwitch/DelBridge", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vSwitchClient) AddBridgePort(ctx context.Context, in *AddBridgePortRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.VSwitch/AddBridgePort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vSwitchClient) DelBridgePort(ctx context.Context, in *DelBridgePortRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.VSwitch/DelBridgePort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VSwitchServer is the server API for VSwitch service.
// All implementations must embed UnimplementedVSwitchServer
// for forward compatibility
type VSwitchServer interface {
	AddBridge(context.Context, *AddBridgeRequest) (*Response, error)
	DelBridge(context.Context, *DelBridgeRequest) (*Response, error)
	AddBridgePort(context.Context, *AddBridgePortRequest) (*Response, error)
	DelBridgePort(context.Context, *DelBridgePortRequest) (*Response, error)
	mustEmbedUnimplementedVSwitchServer()
}

// UnimplementedVSwitchServer must be embedded to have forward compatible implementations.
type UnimplementedVSwitchServer struct {
}

func (UnimplementedVSwitchServer) AddBridge(context.Context, *AddBridgeRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBridge not implemented")
}
func (UnimplementedVSwitchServer) DelBridge(context.Context, *DelBridgeRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelBridge not implemented")
}
func (UnimplementedVSwitchServer) AddBridgePort(context.Context, *AddBridgePortRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBridgePort not implemented")
}
func (UnimplementedVSwitchServer) DelBridgePort(context.Context, *DelBridgePortRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelBridgePort not implemented")
}
func (UnimplementedVSwitchServer) mustEmbedUnimplementedVSwitchServer() {}

// UnsafeVSwitchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VSwitchServer will
// result in compilation errors.
type UnsafeVSwitchServer interface {
	mustEmbedUnimplementedVSwitchServer()
}

func RegisterVSwitchServer(s grpc.ServiceRegistrar, srv VSwitchServer) {
	s.RegisterService(&VSwitch_ServiceDesc, srv)
}

func _VSwitch_AddBridge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBridgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VSwitchServer).AddBridge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VSwitch/AddBridge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VSwitchServer).AddBridge(ctx, req.(*AddBridgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VSwitch_DelBridge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelBridgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VSwitchServer).DelBridge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VSwitch/DelBridge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VSwitchServer).DelBridge(ctx, req.(*DelBridgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VSwitch_AddBridgePort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBridgePortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VSwitchServer).AddBridgePort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VSwitch/AddBridgePort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VSwitchServer).AddBridgePort(ctx, req.(*AddBridgePortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VSwitch_DelBridgePort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelBridgePortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VSwitchServer).DelBridgePort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.VSwitch/DelBridgePort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VSwitchServer).DelBridgePort(ctx, req.(*DelBridgePortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VSwitch_ServiceDesc is the grpc.ServiceDesc for VSwitch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VSwitch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.VSwitch",
	HandlerType: (*VSwitchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBridge",
			Handler:    _VSwitch_AddBridge_Handler,
		},
		{
			MethodName: "DelBridge",
			Handler:    _VSwitch_DelBridge_Handler,
		},
		{
			MethodName: "AddBridgePort",
			Handler:    _VSwitch_AddBridgePort_Handler,
		},
		{
			MethodName: "DelBridgePort",
			Handler:    _VSwitch_DelBridgePort_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}

// OpenflowClient is the client API for Openflow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OpenflowClient interface {
	AddFlow(ctx context.Context, in *AddFlowRequest, opts ...grpc.CallOption) (*Response, error)
	DelFlow(ctx context.Context, in *DelFlowRequest, opts ...grpc.CallOption) (*Response, error)
	SyncFlows(ctx context.Context, in *SyncFlowsRequest, opts ...grpc.CallOption) (*Response, error)
	DumpBridgePort(ctx context.Context, in *DumpBridgePortRequest, opts ...grpc.CallOption) (*DumpBridgePortResponse, error)
	DumpFlows(ctx context.Context, in *DumpFlowsRequest, opts ...grpc.CallOption) (*DumpFlowsResponse, error)
}

type openflowClient struct {
	cc grpc.ClientConnInterface
}

func NewOpenflowClient(cc grpc.ClientConnInterface) OpenflowClient {
	return &openflowClient{cc}
}

func (c *openflowClient) AddFlow(ctx context.Context, in *AddFlowRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.Openflow/AddFlow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openflowClient) DelFlow(ctx context.Context, in *DelFlowRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.Openflow/DelFlow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openflowClient) SyncFlows(ctx context.Context, in *SyncFlowsRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pb.Openflow/SyncFlows", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openflowClient) DumpBridgePort(ctx context.Context, in *DumpBridgePortRequest, opts ...grpc.CallOption) (*DumpBridgePortResponse, error) {
	out := new(DumpBridgePortResponse)
	err := c.cc.Invoke(ctx, "/pb.Openflow/DumpBridgePort", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openflowClient) DumpFlows(ctx context.Context, in *DumpFlowsRequest, opts ...grpc.CallOption) (*DumpFlowsResponse, error) {
	out := new(DumpFlowsResponse)
	err := c.cc.Invoke(ctx, "/pb.Openflow/DumpFlows", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OpenflowServer is the server API for Openflow service.
// All implementations must embed UnimplementedOpenflowServer
// for forward compatibility
type OpenflowServer interface {
	AddFlow(context.Context, *AddFlowRequest) (*Response, error)
	DelFlow(context.Context, *DelFlowRequest) (*Response, error)
	SyncFlows(context.Context, *SyncFlowsRequest) (*Response, error)
	DumpBridgePort(context.Context, *DumpBridgePortRequest) (*DumpBridgePortResponse, error)
	DumpFlows(context.Context, *DumpFlowsRequest) (*DumpFlowsResponse, error)
	mustEmbedUnimplementedOpenflowServer()
}

// UnimplementedOpenflowServer must be embedded to have forward compatible implementations.
type UnimplementedOpenflowServer struct {
}

func (UnimplementedOpenflowServer) AddFlow(context.Context, *AddFlowRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFlow not implemented")
}
func (UnimplementedOpenflowServer) DelFlow(context.Context, *DelFlowRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelFlow not implemented")
}
func (UnimplementedOpenflowServer) SyncFlows(context.Context, *SyncFlowsRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncFlows not implemented")
}
func (UnimplementedOpenflowServer) DumpBridgePort(context.Context, *DumpBridgePortRequest) (*DumpBridgePortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DumpBridgePort not implemented")
}
func (UnimplementedOpenflowServer) DumpFlows(context.Context, *DumpFlowsRequest) (*DumpFlowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DumpFlows not implemented")
}
func (UnimplementedOpenflowServer) mustEmbedUnimplementedOpenflowServer() {}

// UnsafeOpenflowServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OpenflowServer will
// result in compilation errors.
type UnsafeOpenflowServer interface {
	mustEmbedUnimplementedOpenflowServer()
}

func RegisterOpenflowServer(s grpc.ServiceRegistrar, srv OpenflowServer) {
	s.RegisterService(&Openflow_ServiceDesc, srv)
}

func _Openflow_AddFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenflowServer).AddFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Openflow/AddFlow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenflowServer).AddFlow(ctx, req.(*AddFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Openflow_DelFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenflowServer).DelFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Openflow/DelFlow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenflowServer).DelFlow(ctx, req.(*DelFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Openflow_SyncFlows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncFlowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenflowServer).SyncFlows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Openflow/SyncFlows",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenflowServer).SyncFlows(ctx, req.(*SyncFlowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Openflow_DumpBridgePort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpBridgePortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenflowServer).DumpBridgePort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Openflow/DumpBridgePort",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenflowServer).DumpBridgePort(ctx, req.(*DumpBridgePortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Openflow_DumpFlows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpFlowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenflowServer).DumpFlows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Openflow/DumpFlows",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenflowServer).DumpFlows(ctx, req.(*DumpFlowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Openflow_ServiceDesc is the grpc.ServiceDesc for Openflow service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Openflow_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Openflow",
	HandlerType: (*OpenflowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddFlow",
			Handler:    _Openflow_AddFlow_Handler,
		},
		{
			MethodName: "DelFlow",
			Handler:    _Openflow_DelFlow_Handler,
		},
		{
			MethodName: "SyncFlows",
			Handler:    _Openflow_SyncFlows_Handler,
		},
		{
			MethodName: "DumpBridgePort",
			Handler:    _Openflow_DumpBridgePort_Handler,
		},
		{
			MethodName: "DumpFlows",
			Handler:    _Openflow_DumpFlows_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
