# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import agent_pb2 as agent__pb2


class VSwitchStub(object):
    """TODO add comment: idempotency

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddBridge = channel.unary_unary(
                '/pb.VSwitch/AddBridge',
                request_serializer=agent__pb2.AddBridgeRequest.SerializeToString,
                response_deserializer=agent__pb2.Response.FromString,
                )
        self.DelBridge = channel.unary_unary(
                '/pb.VSwitch/DelBridge',
                request_serializer=agent__pb2.DelBridgeRequest.SerializeToString,
                response_deserializer=agent__pb2.Response.FromString,
                )
        self.AddBridgePort = channel.unary_unary(
                '/pb.VSwitch/AddBridgePort',
                request_serializer=agent__pb2.AddBridgePortRequest.SerializeToString,
                response_deserializer=agent__pb2.Response.FromString,
                )
        self.DelBridgePort = channel.unary_unary(
                '/pb.VSwitch/DelBridgePort',
                request_serializer=agent__pb2.DelBridgePortRequest.SerializeToString,
                response_deserializer=agent__pb2.Response.FromString,
                )


class VSwitchServicer(object):
    """TODO add comment: idempotency

    """

    def AddBridge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DelBridge(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBridgePort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DelBridgePort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VSwitchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddBridge': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBridge,
                    request_deserializer=agent__pb2.AddBridgeRequest.FromString,
                    response_serializer=agent__pb2.Response.SerializeToString,
            ),
            'DelBridge': grpc.unary_unary_rpc_method_handler(
                    servicer.DelBridge,
                    request_deserializer=agent__pb2.DelBridgeRequest.FromString,
                    response_serializer=agent__pb2.Response.SerializeToString,
            ),
            'AddBridgePort': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBridgePort,
                    request_deserializer=agent__pb2.AddBridgePortRequest.FromString,
                    response_serializer=agent__pb2.Response.SerializeToString,
            ),
            'DelBridgePort': grpc.unary_unary_rpc_method_handler(
                    servicer.DelBridgePort,
                    request_deserializer=agent__pb2.DelBridgePortRequest.FromString,
                    response_serializer=agent__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.VSwitch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VSwitch(object):
    """TODO add comment: idempotency

    """

    @staticmethod
    def AddBridge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.VSwitch/AddBridge',
            agent__pb2.AddBridgeRequest.SerializeToString,
            agent__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DelBridge(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.VSwitch/DelBridge',
            agent__pb2.DelBridgeRequest.SerializeToString,
            agent__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddBridgePort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.VSwitch/AddBridgePort',
            agent__pb2.AddBridgePortRequest.SerializeToString,
            agent__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DelBridgePort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.VSwitch/DelBridgePort',
            agent__pb2.DelBridgePortRequest.SerializeToString,
            agent__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class OpenflowStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddFlow = channel.unary_unary(
                '/pb.Openflow/AddFlow',
                request_serializer=agent__pb2.AddFlowRequest.SerializeToString,
                response_deserializer=agent__pb2.Response.FromString,
                )
        self.DelFlow = channel.unary_unary(
                '/pb.Openflow/DelFlow',
                request_serializer=agent__pb2.DelFlowRequest.SerializeToString,
                response_deserializer=agent__pb2.Response.FromString,
                )
        self.SyncFlows = channel.unary_unary(
                '/pb.Openflow/SyncFlows',
                request_serializer=agent__pb2.SyncFlowsRequest.SerializeToString,
                response_deserializer=agent__pb2.Response.FromString,
                )
        self.DumpBridgePort = channel.unary_unary(
                '/pb.Openflow/DumpBridgePort',
                request_serializer=agent__pb2.DumpBridgePortRequest.SerializeToString,
                response_deserializer=agent__pb2.DumpBridgePortResponse.FromString,
                )
        self.DumpFlows = channel.unary_unary(
                '/pb.Openflow/DumpFlows',
                request_serializer=agent__pb2.DumpFlowsRequest.SerializeToString,
                response_deserializer=agent__pb2.DumpFlowsResponse.FromString,
                )


class OpenflowServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddFlow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DelFlow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncFlows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DumpBridgePort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DumpFlows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OpenflowServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddFlow': grpc.unary_unary_rpc_method_handler(
                    servicer.AddFlow,
                    request_deserializer=agent__pb2.AddFlowRequest.FromString,
                    response_serializer=agent__pb2.Response.SerializeToString,
            ),
            'DelFlow': grpc.unary_unary_rpc_method_handler(
                    servicer.DelFlow,
                    request_deserializer=agent__pb2.DelFlowRequest.FromString,
                    response_serializer=agent__pb2.Response.SerializeToString,
            ),
            'SyncFlows': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncFlows,
                    request_deserializer=agent__pb2.SyncFlowsRequest.FromString,
                    response_serializer=agent__pb2.Response.SerializeToString,
            ),
            'DumpBridgePort': grpc.unary_unary_rpc_method_handler(
                    servicer.DumpBridgePort,
                    request_deserializer=agent__pb2.DumpBridgePortRequest.FromString,
                    response_serializer=agent__pb2.DumpBridgePortResponse.SerializeToString,
            ),
            'DumpFlows': grpc.unary_unary_rpc_method_handler(
                    servicer.DumpFlows,
                    request_deserializer=agent__pb2.DumpFlowsRequest.FromString,
                    response_serializer=agent__pb2.DumpFlowsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.Openflow', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Openflow(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddFlow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.Openflow/AddFlow',
            agent__pb2.AddFlowRequest.SerializeToString,
            agent__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DelFlow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.Openflow/DelFlow',
            agent__pb2.DelFlowRequest.SerializeToString,
            agent__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SyncFlows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.Openflow/SyncFlows',
            agent__pb2.SyncFlowsRequest.SerializeToString,
            agent__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DumpBridgePort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.Openflow/DumpBridgePort',
            agent__pb2.DumpBridgePortRequest.SerializeToString,
            agent__pb2.DumpBridgePortResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DumpFlows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.Openflow/DumpFlows',
            agent__pb2.DumpFlowsRequest.SerializeToString,
            agent__pb2.DumpFlowsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
